USE WAREHOUSE DEFI_WH;
USE DATABASE DEFI_DB;
USE SCHEMA RAW;

COPY INTO RAW_UNISWAP_SWAPS
FROM @UNISWAP_STAGE/uniswap_swaps_processed.csv
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'CONTINUE';