CREATE WAREHOUSE IF NOT EXISTS DEFI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DEFI_DB;

CREATE SCHEMA IF NOT EXISTS DEFI_DB.RAW;
CREATE SCHEMA IF NOT EXISTS DEFI_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS DEFI_DB.MARTS;

USE WAREHOUSE DEFI_WH;
USE DATABASE DEFI_DB;