USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION defi_s3_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = (
    's3://johnson-defi-data-pipeline-jc-2026/'
);